name: PyQt6 CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytest PyQt6

      - name: Run tests
        run: pytest

      - name: Build .exe with PyInstaller
        if: success()
        run: |
          pyinstaller --onefile --noconsole main_qt.py
          echo "✅ Build complete: dist/main_qt.exe"

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyQt6_Calculator_Executable
          path: dist/main_qt.exe
